### PR TITLE
feat(server)!: rename .func() to .handler()

### PR DESCRIPTION
**Pull request by unteifu**
I think the `.func()` function should be renamed to `.handler()` as visually it doesn't make sense at first and looks very vague, this was something I found confusing when I first saw the docs. Calling it `.handler()` means developers, know ok this is what will be the endpoints main handling logic after all middleware and validation.

### CODE REVIEW

**Comment by unnoq** [comment]
oRPC start with `.handler` but has been rename to `.func` because it describe widely ability of oRPC (you can call directly procedure as native function).

But it only is my opinion, and English is not my first language so I will carefully consider it

**Comment by unnoq** [comment]
`.handler`, `ORPCHandler`, and `OpenAPIHandler` seem conflict name here

**Comment by unteifu** [comment]
> `.handler`, `ORPCHandler`, and `OpenAPIHandler` seem conflict name here

I think that's completely fine to have still because it still runs on the basis of "this is the function/codeblock that handles the logic", like OpenAPIHandler handles that specifically and you know that middleware will do that.

**Comment by unnoq** [comment]
@unteifu please resolve conflict, and go to `apps/content` run `pnpm run build` and I will merge this!

**Comment by unteifu** [comment]
I've just merged the docs update with this branch as it means the docs will be up to date with this commit then

**Pull request merged**
